# -*- coding: utf-8 -*-
"""Data_Cleaning_Reporting_Automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gldLeks3u4wuEQ-8z05FbpFjs0VKiW6a

**Data Cleaning & Reporting Automation**

1. Introduction

Data cleaning and reporting are important steps in data analysis. Raw datasets often contain missing values, duplicate records, inconsistent information, and invalid dates. These problems can affect the accuracy of analysis and reports.

This project focuses on developing an automated data cleaning and reporting workflow using Python, Pandas, Matplotlib, and Excel. The system cleans the raw sales data, performs analysis, generates visualizations, and creates an automated Excel report.

2. Problem Statement

Manually cleaning and preparing datasets can take considerable time and may lead to errors.

The objective of this project is to automate the process of:

Identifying missing values
Detecting duplicate records
Handling invalid dates
Cleaning inconsistent data
Generating sales summaries
Creating visualizations
Producing an Excel report
3. Objectives

The main objectives are:

Load and inspect the raw sales dataset.
Identify data quality problems.
Handle missing values.
Remove duplicate records.
Handle invalid dates.
Standardize inconsistent data.
Generate useful sales statistics.
Create visualizations.
Automatically generate an Excel report.
Reduce manual effort in data preparation and reporting.
4. Tools and Technologies
Tool	Purpose
Python	Data processing and automation
Pandas	Data cleaning and analysis
NumPy	Numerical operations
Matplotlib	Data visualization
OpenPyXL	Excel report generation
Google Colab	Development environment
Excel	Final reporting
5. Dataset

The project uses a sample/synthetic sales dataset containing sales transaction information.

The dataset includes fields such as:

Order ID
Order Date
Customer Name
Segment
City
Region
Category
Sub-Category
Product Name
Quantity
Sales
Discount

The dataset was intentionally prepared with data-quality issues so that the cleaning and automation workflow could be demonstrated.

6. Data Cleaning Process

The following steps were performed:

Missing Values

Missing values were identified using:

df.isnull().sum()

Appropriate values were then used to fill missing information.

Duplicate Records

Duplicate rows were identified using:

df.duplicated().sum()

Duplicate records were removed using:

df.drop_duplicates()
Invalid Dates

Order dates were converted into proper date format:

pd.to_datetime(df["Order_Date"], errors="coerce")

Invalid dates were then handled during the cleaning process.

Inconsistent Data

Text fields such as Category and City were standardized by removing unnecessary spaces and standardizing capitalization.

Example:

cleaned_df["City"] = cleaned_df["City"].str.strip()
7. Data Analysis

After cleaning the dataset, several analyses were performed.

Sales Summary

The system calculates:

Total Sales
Total Orders
Total Customers
Total Quantity
Average Sale
Category Analysis

Sales were grouped according to product category to understand category-level sales.

Regional Analysis

Sales were grouped by region to analyze regional performance.

Monthly Analysis

Sales were grouped by month to identify changes in sales over time.

Product Analysis

The top 10 products were identified based on total sales.

8. Data Visualization

The project generates the following visualizations:

Sales by Category
Sales by Region
Monthly Sales Trend
Top 10 Products by Sales

These charts make the analysis easier to understand and provide a visual summary of the cleaned data.

9. Automated Reporting

After cleaning and analyzing the data, the project automatically generates an Excel report.

The final Excel report contains:

Cleaning Summary
Sales Summary
Cleaned Data
Category Analysis
Region Analysis
Monthly Analysis
Top Products

This reduces the need to manually prepare reports every time the dataset is processed.

10. Project Workflow
Raw Dataset
     ↓
Load Dataset
     ↓
Data Quality Check
     ↓
Missing Value Detection
     ↓
Duplicate Detection
     ↓
Invalid Date Detection
     ↓
Data Cleaning
     ↓
Clean Dataset
     ↓
Data Analysis
     ↓
Visualization
     ↓
Automated Excel Report
11. Results

The project successfully demonstrates an automated workflow for cleaning and reporting sales data.

The system is able to identify and handle common data-quality issues, perform sales analysis, generate charts, and produce an Excel report automatically.

The workflow makes the reporting process more organized and reduces repetitive manual work.

12. Advantages
Reduces manual data-cleaning work
Saves time
Provides consistent processing
Makes data-quality problems easier to identify
Generates reports automatically
Provides visual summaries
Can be reused with similar datasets
13. Limitations
The project currently uses a sample/synthetic dataset.
The cleaning rules are designed for this dataset structure.
More complex real-world datasets may require additional validation rules.
The generated report is currently focused on sales-related analysis.
14. Future Scope

The project can be improved by:

Connecting directly to databases
Adding automated scheduled reports
Creating an interactive Power BI dashboard
Adding email-based report delivery
Supporting larger datasets
Adding more data-quality validation rules
Creating a web-based reporting interface
15. Conclusion

The Data Cleaning & Reporting Automation project demonstrates how Python can be used to automate important data-processing and reporting tasks.

The system identifies data-quality issues, cleans the dataset, performs analysis, creates visualizations, and generates an Excel report. This workflow provides a structured approach to transforming raw data into useful information while reducing repetitive manual reporting work.

step 1 -->

Load the dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("raw_sales_data_dirty.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

"""step 2 -->

Check the dataset information
"""

print("Dataset Information:")
print(df.info())

"""Check Missing Values and Duplicates"""

# Check missing values
missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

"""Check duplicate records"""

# Check duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

"""Check invalid dates"""

# Convert Order_Date to datetime
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

# Count invalid dates
invalid_dates = df["Order_Date"].isnull().sum()

print("Invalid dates:", invalid_dates)

"""Create a simple data-quality summary"""

print("----- DATA QUALITY SUMMARY -----")
print("Total rows:", len(df))
print("Total columns:", len(df.columns))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Invalid dates:", df["Order_Date"].isnull().sum())

"""step 3-->

Clean the Dataset
"""

# ==========================================
# STEP 4: DATA CLEANING
# ==========================================

# Make a copy of the raw dataset
cleaned_df = df.copy()

# 1. Remove duplicate rows
before_duplicates = len(cleaned_df)

cleaned_df = cleaned_df.drop_duplicates()

after_duplicates = len(cleaned_df)

print("Duplicate rows removed:", before_duplicates - after_duplicates)


# 2. Handle missing Customer Names
cleaned_df["Customer_Name"] = cleaned_df["Customer_Name"].fillna("Unknown")


# 3. Handle missing Region
cleaned_df["Region"] = cleaned_df["Region"].fillna(
    cleaned_df["Region"].mode()[0]
)


# 4. Handle missing Sales
cleaned_df["Sales"] = cleaned_df["Sales"].fillna(
    cleaned_df["Sales"].median()
)


# 5. Clean text spaces
cleaned_df["City"] = cleaned_df["City"].str.strip()
cleaned_df["Category"] = cleaned_df["Category"].str.strip()


# 6. Standardize Category names
cleaned_df["Category"] = cleaned_df["Category"].str.title()


# 7. Handle invalid dates
# Invalid dates were converted to NaT in Step 3.
# Fill them using the most common valid date.
cleaned_df["Order_Date"] = cleaned_df["Order_Date"].fillna(
    cleaned_df["Order_Date"].median()
)


# 8. Sort data by Order Date
cleaned_df = cleaned_df.sort_values("Order_Date")


# 9. Reset row numbers
cleaned_df = cleaned_df.reset_index(drop=True)


# ==========================================
# CLEANING SUMMARY
# ==========================================

print("\n========== CLEANING COMPLETED ==========")

print("Rows before cleaning:", len(df))
print("Rows after cleaning:", len(cleaned_df))

print("\nMissing values after cleaning:")
print(cleaned_df.isnull().sum())

print("\nDuplicate rows after cleaning:")
print(cleaned_df.duplicated().sum())

print("\nCleaned dataset preview:")
display(cleaned_df.head())

""" Verify cleaning"""

print("Remaining missing values:",
      cleaned_df.isnull().sum().sum())

print("Remaining duplicate rows:",
      cleaned_df.duplicated().sum())

"""Save the cleaned dataset"""

cleaned_df.to_csv("cleaned_sales_data.csv", index=False)

print("Cleaned dataset saved successfully!")

""" step 4--> Create the Automated Sales Report

 Create basic business summary
"""

# ==========================================
# STEP 5: AUTOMATED SALES REPORT
# ==========================================

total_sales = cleaned_df["Sales"].sum()
total_orders = cleaned_df["Order_ID"].nunique()
total_customers = cleaned_df["Customer_Name"].nunique()
total_quantity = cleaned_df["Quantity"].sum()
average_sales = cleaned_df["Sales"].mean()

print("========== SALES REPORT ==========")
print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Total Orders      : {total_orders}")
print(f"Total Customers   : {total_customers}")
print(f"Total Quantity    : {total_quantity}")
print(f"Average Sale      : ₹{average_sales:,.2f}")

"""Sales by Category"""

# Sales by Category

category_sales = (
    cleaned_df.groupby("Category")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("========== SALES BY CATEGORY ==========")
print(category_sales)

"""Sales by Region"""

# Sales by Region

region_sales = (
    cleaned_df.groupby("Region")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("========== SALES BY REGION ==========")
print(region_sales)

"""Monthly Sales"""

# Monthly Sales

cleaned_df["Month"] = cleaned_df["Order_Date"].dt.to_period("M")

monthly_sales = (
    cleaned_df.groupby("Month")["Sales"]
    .sum()
    .reset_index()
)

monthly_sales["Month"] = monthly_sales["Month"].astype(str)

print("========== MONTHLY SALES ==========")
display(monthly_sales)

"""Top 10 Products"""

# Top 10 Products

top_products = (
    cleaned_df.groupby("Product_Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print("========== TOP 10 PRODUCTS ==========")
print(top_products)

"""Create one complete report"""

# ==========================================
# COMPLETE AUTOMATED REPORT
# ==========================================

report = {
    "Total Sales": total_sales,
    "Total Orders": total_orders,
    "Total Customers": total_customers,
    "Total Quantity": total_quantity,
    "Average Sale": average_sales
}

report_df = pd.DataFrame(
    report.items(),
    columns=["Metric", "Value"]
)

print("========== AUTOMATED SALES REPORT ==========")
display(report_df)

"""step 5--> Create Professional Visualizations

Sales by Category
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

category_sales.plot(kind="bar")

plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

"""Sales by Region"""

plt.figure(figsize=(8,5))

region_sales.plot(kind="bar")

plt.title("Sales by Region")
plt.xlabel("Region")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.tight_layout()

plt.show()

"""Monthly Sales Trend"""

plt.figure(figsize=(10,5))

plt.plot(
    monthly_sales["Month"],
    monthly_sales["Sales"],
    marker="o"
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()

plt.show()

"""Top 10 Products"""

plt.figure(figsize=(10,6))

top_products.sort_values().plot(kind="barh")

plt.title("Top 10 Products by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Product")
plt.tight_layout()

plt.show()

"""Create One Professional Dashboard"""

fig, axes = plt.subplots(2, 2, figsize=(16, 10))

# 1. Sales by Category
category_sales.plot(
    kind="bar",
    ax=axes[0, 0]
)
axes[0, 0].set_title("Sales by Category")
axes[0, 0].set_xlabel("Category")
axes[0, 0].set_ylabel("Total Sales")
axes[0, 0].tick_params(axis="x", rotation=0)

# 2. Sales by Region
region_sales.plot(
    kind="bar",
    ax=axes[0, 1]
)
axes[0, 1].set_title("Sales by Region")
axes[0, 1].set_xlabel("Region")
axes[0, 1].set_ylabel("Total Sales")
axes[0, 1].tick_params(axis="x", rotation=0)

# 3. Monthly Sales
axes[1, 0].plot(
    monthly_sales["Month"],
    monthly_sales["Sales"],
    marker="o"
)
axes[1, 0].set_title("Monthly Sales Trend")
axes[1, 0].set_xlabel("Month")
axes[1, 0].set_ylabel("Total Sales")
axes[1, 0].tick_params(axis="x", rotation=45)
axes[1, 0].grid(True)

# 4. Top 10 Products
top_products.sort_values().plot(
    kind="barh",
    ax=axes[1, 1]
)
axes[1, 1].set_title("Top 10 Products")
axes[1, 1].set_xlabel("Total Sales")
axes[1, 1].set_ylabel("Product")

plt.suptitle(
    "Automated Sales Analysis Dashboard",
    fontsize=18
)

plt.tight_layout()
plt.show()

"""step 6--> Generate an Automated Excel Report

Install/openpyxl
"""

!pip install openpyxl -q

"""Generate the Excel Report"""

import pandas as pd

output_file = "Automated_Sales_Report.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    # 1. Summary Report
    report_df.to_excel(
        writer,
        sheet_name="Summary Report",
        index=False
    )

    # 2. Cleaned Data
    cleaned_df.to_excel(
        writer,
        sheet_name="Cleaned Data",
        index=False
    )

    # 3. Sales by Category
    category_sales.reset_index().to_excel(
        writer,
        sheet_name="Sales by Category",
        index=False
    )

    # 4. Sales by Region
    region_sales.reset_index().to_excel(
        writer,
        sheet_name="Sales by Region",
        index=False
    )

    # 5. Monthly Sales
    monthly_sales.to_excel(
        writer,
        sheet_name="Monthly Sales",
        index=False
    )

    # 6. Top 10 Products
    top_products.reset_index().to_excel(
        writer,
        sheet_name="Top 10 Products",
        index=False
    )

print("Excel report created successfully!")
print("File name:", output_file)

"""Make the Excel Report Professional"""

from openpyxl import load_workbook
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter

# Load workbook
wb = load_workbook("Automated_Sales_Report.xlsx")

# Format every sheet
for ws in wb.worksheets:

    # Header formatting
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="center")

    # Adjust column widths
    for column in ws.columns:
        max_length = 0
        column_letter = get_column_letter(column[0].column)

        for cell in column:
            if cell.value is not None:
                max_length = max(
                    max_length,
                    len(str(cell.value))
                )

        ws.column_dimensions[column_letter].width = min(
            max_length + 2,
            40
        )

# Save formatted workbook
wb.save("Automated_Sales_Report.xlsx")

print("Professional Excel report created successfully!")

"""Download the Excel Report"""

from google.colab import files

files.download("Automated_Sales_Report.xlsx")

"""step 7--> Create the Final Automated Report

Create Data Cleaning Summary
"""

# Data cleaning statistics

rows_before = len(df)
rows_after = len(cleaned_df)

missing_before = df.isnull().sum().sum()
missing_after = cleaned_df.isnull().sum().sum()

duplicates_before = df.duplicated().sum()
duplicates_after = cleaned_df.duplicated().sum()

invalid_dates = df["Order_Date"].isnull().sum()

cleaning_summary = pd.DataFrame({
    "Metric": [
        "Rows Before Cleaning",
        "Rows After Cleaning",
        "Missing Values Before",
        "Missing Values After",
        "Duplicate Rows Before",
        "Duplicate Rows After",
        "Invalid Dates"
    ],
    "Value": [
        rows_before,
        rows_after,
        missing_before,
        missing_after,
        duplicates_before,
        duplicates_after,
        invalid_dates
    ]
})

print("========== DATA CLEANING SUMMARY ==========")
display(cleaning_summary)

"""Create Final Project Summary"""

final_summary = pd.DataFrame({
    "Metric": [
        "Total Sales",
        "Total Orders",
        "Total Customers",
        "Total Quantity",
        "Average Sale"
    ],
    "Value": [
        total_sales,
        total_orders,
        total_customers,
        total_quantity,
        average_sales
    ]
})

print("========== FINAL SALES SUMMARY ==========")
display(final_summary)

"""Put Everything Into One Final Excel File"""

final_file = "Final_Data_Cleaning_Reporting_Report.xlsx"

with pd.ExcelWriter(final_file, engine="openpyxl") as writer:

    # Cleaning summary
    cleaning_summary.to_excel(
        writer,
        sheet_name="Cleaning Summary",
        index=False
    )

    # Sales summary
    final_summary.to_excel(
        writer,
        sheet_name="Sales Summary",
        index=False
    )

    # Cleaned dataset
    cleaned_df.to_excel(
        writer,
        sheet_name="Cleaned Data",
        index=False
    )

    # Category analysis
    category_sales.reset_index().to_excel(
        writer,
        sheet_name="Category Analysis",
        index=False
    )

    # Region analysis
    region_sales.reset_index().to_excel(
        writer,
        sheet_name="Region Analysis",
        index=False
    )

    # Monthly analysis
    monthly_sales.to_excel(
        writer,
        sheet_name="Monthly Analysis",
        index=False
    )

    # Top products
    top_products.reset_index().to_excel(
        writer,
        sheet_name="Top Products",
        index=False
    )

print("Final automated report created successfully!")
print(final_file)

"""Format the Final Excel Report"""

from openpyxl import load_workbook
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter

wb = load_workbook(final_file)

for ws in wb.worksheets:

    # Bold headers
    for cell in ws[1]:
        cell.font = Font(bold=True)
        cell.alignment = Alignment(horizontal="center")

    # Adjust column widths
    for column in ws.columns:

        max_length = 0
        column_letter = get_column_letter(column[0].column)

        for cell in column:
            if cell.value is not None:
                max_length = max(
                    max_length,
                    len(str(cell.value))
                )

        ws.column_dimensions[column_letter].width = min(
            max_length + 2,
            40
        )

wb.save(final_file)

print("Final Excel report formatted successfully!")

"""Download Your Final Report"""

from google.colab import files

files.download(final_file)